# Generated by Django 3.2 on 2021-05-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comments'),
        ('profiles', '0003_auto_20210504_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarked',
            field=models.ManyToManyField(to='article.Article'),
        ),
    ]
