# Generated by Django 3.2 on 2021-05-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_comments_article'),
        ('profiles', '0005_alter_profile_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarked',
            field=models.ManyToManyField(to='article.Article'),
        ),
    ]
