# Generated by Django 3.2 on 2021-05-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_savearticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveArticle',
        ),
    ]
