# Generated by Django 3.2 on 2021-05-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='contet',
            new_name='content',
        ),
    ]
