# Generated by Django 3.2 on 2021-05-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_comments_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
